export type TaskStatus = "pending" | "completed" | "upcoming"
export type TaskPriority = "high" | "medium" | "low"
export type SortOption = "priority" | "dueDate" | "status"

export interface Task {
  id: number
  title: string
  description: string
  status: TaskStatus
  priority: TaskPriority
  dueDate: string
  linkedCase: {
    id: string
    title: string
  }
  isAutoGenerated: boolean
}